# Change these first
owner: ayalon # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: famillesuisse.ch
    url: https://famillesuisse.ch
  - name: lessmess.io
    url: https://lessmess.io
  - name: haltefest.ch
    url: https://haltefest.ch
  - name: ayalon.ch
    url: https://ayalon.ch
  - name: xtramarketing.ch
    url: https://xtramarketing.ch
  - name: jira.ayalon.ch
    url: https://jira.ayalon.ch

assignees:
  - ayalon

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://ayalon.ch/sites/all/themes/custom/ayalon_bootstrap/logo.png
  name: Status Website
  introTitle: "**Uptime Monitor** by ayalon GmbH."
  introMessage: "Monitors website's uptime and get downtime notifications"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
